---
version: "3.9"

name: "plex-reshare"

services:
  plex_reshare:
    image: "peterbuga/plex-reshare:latest"
    container_name: "plex_reshare"
    hostname: "plex_reshare"
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - 6379:6379
      - 8080:8080
      # - 8000:8000  # mapping to starlette, for debugging mostly
    logging:
      options:
        max-size: "5m"

    volumes:
      - "./:/pr"

    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 2g

      # enable for development
      # - "./app:/app"
      # - "./rq:/rq"
      # - "./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro"
      # - "./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro"
      # - "./supervisord.conf:/etc/supervisord.conf"
